% load FD scaling
EXPORT = lib.require(@lib.model.tov.fd.scale);


% ANCH = lib.require(@lib.model.tov.rar.anchor);
% MAP  = lib.require(@lib.model.tov.rar.map);
% 
% % SURFACE SCALE
% fscale = @(obj,ykey) 1/ANCH.surface.map(obj,ykey);
% 
% EXPORT.surface.radius = lib.module.ProfileMapping(...
% 	@(obj) fscale(obj,'radius'),...
% 	'r_s'...
% );
% 
% EXPORT.surface.mass = lib.module.ProfileMapping(...
% 	@(obj) fscale(obj,MAP.mass),...
% 	'M_s'...
% );
% 
% EXPORT.surface.velocity = lib.module.ProfileMapping(...
% 	@(obj) fscale(obj,MAP.velocity),...
% 	'v_s'...
% );

MAP  = lib.require(@lib.model.tov.rar.map);

% SURFACE SCALE
fScale = @(Y) 1/Y(end);

EXPORT.surface.radius = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.radius.map(obj)),...
	'r_s'...
);

EXPORT.surface.mass = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.mass.map(obj)),...
	'M_s'...
);

EXPORT.surface.velocity = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.velocity.map(obj)),...
	'v_s'...
);